In [1]:
#q1
# reshaping , viewing, stacking, squeezing and unsqueezing

import torch

a = torch.tensor([1,2,3,4,5,6])
print('before reshape : ',a)

a = a.reshape([3,2])
print('after reshape : ',a)

b = torch.tensor([1,2,3,4,5,6,7,8,9])
print('view: ' ,b.view(3,3))

c1= torch.tensor([1,2,3])
c2 = torch.tensor([4,5,6])
c = torch.stack((c1,c2), dim=0)
print('stack (dim 0): \n' ,c)

c = torch.stack((c1,c2), dim=1)
print('stack (dim 1): \n' ,c)


d1 = torch.randn(3,1,2,1,5)
d = torch.squeeze(d1)
print('d.size() = ',d.size())

e1 = torch.arange(8, dtype=torch.float)
print('e1 = ', e1)

e = torch.unsqueeze(e1, dim=0)
print('unsqueeze dim =0 :  ', e.size())

e = torch.unsqueeze(e1, dim=1)
print('unsqueeze dim =1 :  ', e.size())

before reshape :  tensor([1, 2, 3, 4, 5, 6])
after reshape :  tensor([[1, 2],
        [3, 4],
        [5, 6]])
view:  tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
stack (dim 0): 
 tensor([[1, 2, 3],
        [4, 5, 6]])
stack (dim 1): 
 tensor([[1, 4],
        [2, 5],
        [3, 6]])
d.size() =  torch.Size([3, 2, 5])
e1 =  tensor([0., 1., 2., 3., 4., 5., 6., 7.])
unsqueeze dim =0 :   torch.Size([1, 8])
unsqueeze dim =1 :   torch.Size([8, 1])


In [2]:
#q2 use of permute

# creating a tensor with random
# values of dimension 3 X 5 X 2
input_var = torch.randn(3, 5, 2)

# print size
print(input_var.size())

print(input_var)

# dimensions permuted
input_var = input_var.permute(2, 0, 1)

# print size
print(input_var.size())

print(input_var)

torch.Size([3, 5, 2])
tensor([[[-0.3712,  0.1158],
         [ 0.1347, -1.5485],
         [ 2.0427, -0.5309],
         [-1.9613,  1.0704],
         [-1.2345,  2.1298]],

        [[-0.5957,  0.7224],
         [ 1.3207, -0.5949],
         [ 2.0703, -1.2171],
         [ 1.5049,  0.3571],
         [-0.3090,  0.8337]],

        [[-1.6359, -0.7557],
         [ 1.0387,  0.4383],
         [-1.6507, -1.8813],
         [ 0.9250,  0.2596],
         [-0.0795, -1.5739]]])
torch.Size([2, 3, 5])
tensor([[[-0.3712,  0.1347,  2.0427, -1.9613, -1.2345],
         [-0.5957,  1.3207,  2.0703,  1.5049, -0.3090],
         [-1.6359,  1.0387, -1.6507,  0.9250, -0.0795]],

        [[ 0.1158, -1.5485, -0.5309,  1.0704,  2.1298],
         [ 0.7224, -0.5949, -1.2171,  0.3571,  0.8337],
         [-0.7557,  0.4383, -1.8813,  0.2596, -1.5739]]])


In [3]:
#q3 indexing

import torch

tensor = torch.tensor([[1,5,3],[8,9,2]])

print(tensor)

print('at 1,0 = ' ,tensor[1,0])
print('at 1 = ' ,tensor[1])

tensor([[1, 5, 3],
        [8, 9, 2]])
at 1,0 =  tensor(8)
at 1 =  tensor([8, 9, 2])


In [4]:
#q4 numpy array to tensor and back to numpy array
import torch
import numpy as np

npx = np.array([[1,2,3],[5,6,6], [7,8,9]])
print(npx, type(npx))

# change to tensor
t = torch.from_numpy(npx)

print(t, type(t))

npy = t.numpy()

print(npy, type(npy))

[[1 2 3]
 [5 6 6]
 [7 8 9]] <class 'numpy.ndarray'>
tensor([[1, 2, 3],
        [5, 6, 6],
        [7, 8, 9]]) <class 'torch.Tensor'>
[[1 2 3]
 [5 6 6]
 [7 8 9]] <class 'numpy.ndarray'>


In [5]:
#q5 random tensor of size 7 X 7
import torch

random_tensor = torch.rand(7,7)

print(random_tensor, random_tensor.shape)

tensor([[0.4152, 0.5480, 0.7939, 0.1897, 0.5004, 0.6361, 0.7866],
        [0.5927, 0.9243, 0.3594, 0.0469, 0.9758, 0.9420, 0.2398],
        [0.9113, 0.8400, 0.0848, 0.8400, 0.3023, 0.4781, 0.2671],
        [0.7391, 0.5905, 0.1731, 0.5491, 0.8344, 0.9473, 0.6581],
        [0.9242, 0.2861, 0.9584, 0.9947, 0.7999, 0.6618, 0.1721],
        [0.7756, 0.0497, 0.2972, 0.6072, 0.6198, 0.1110, 0.5041],
        [0.6662, 0.2363, 0.2899, 0.6562, 0.8940, 0.9716, 0.5378]]) torch.Size([7, 7])


In [6]:
#q6 MATRIX MULTI
#Define the tensor 'a' from the previous code
a = torch.rand(7,7)

# Define a random tensor of shape (1, 7)
b = torch.rand(1, 7)
b=b.transpose(0,1)
# Perform matrix multiplication
result = torch.matmul(a, b) 

# Print the result
print("Result of matrix multiplication:")
print(result)

Result of matrix multiplication:
tensor([[1.8862],
        [1.7897],
        [1.7896],
        [2.3647],
        [1.8906],
        [1.0407],
        [2.6713]])


In [7]:
#Q7 SENDING TO GPU
# generate 2 random tensors of size 3X2 and send them to gpu

import torch

a = torch.rand(2,3)
b = torch.rand(2,3)

print('a.device = ',a.device)
print('b.device = ',b.device)

# send to gpu
print(torch.cuda.is_available())

if torch.cuda.is_available():
   a = a.cuda()
   b = b.cuda()

print('a.device = ',a.device)
print('b.device = ',b.device)

a.device =  cpu
b.device =  cpu
True
a.device =  cuda:0
b.device =  cuda:0


In [8]:
#Q8
a = torch.rand(7,7)

# Define a random tensor of shape (1, 7)
b = torch.rand(1, 7)
b=b.transpose(0,1)
# Perform matrix multiplication
result = torch.matmul(a, b) 

# Print the result
print("Result of matrix multiplication:")
print(result)
print('a.device = ',a.device)
print('b.device = ',b.device)

# send to gpu
print(torch.cuda.is_available())

if torch.cuda.is_available():
   a = a.cuda()
   b = b.cuda()

print('a.device = ',a.device)
print('b.device = ',b.device)

Result of matrix multiplication:
tensor([[1.3502],
        [1.3084],
        [1.0541],
        [1.2798],
        [1.3370],
        [1.7833],
        [1.6040]])
a.device =  cpu
b.device =  cpu
True
a.device =  cuda:0
b.device =  cuda:0


In [9]:
#Q9

a = torch.rand(2, 3)
b = torch.rand(2, 3)
# Element-wise sum
result = a + b
# Find maximum and minimum values
max_value = torch.max(result)
min_value = torch.min(result)
# Print the result
print("Element-wise sum:")
print(result)
# Print maximum and minimum values
print("Maximum value:", max_value.item())
print("Minimum value:", min_value.item())

print('a.device = ',a.device)
print('b.device = ',b.device)
print(torch.cuda.is_available())
if torch.cuda.is_available():
   a = a.cuda()
   b = b.cuda()
print('a.device = ',a.device)
print('b.device = ',b.device)

Element-wise sum:
tensor([[0.6590, 1.3127, 0.6633],
        [1.2947, 0.5840, 0.9037]])
Maximum value: 1.3126916885375977
Minimum value: 0.5839519500732422
a.device =  cpu
b.device =  cpu
True
a.device =  cuda:0
b.device =  cuda:0


In [10]:
#q10
a = torch.rand(2, 3)
b = torch.rand(2, 3)

c = a + b

# Find the index of the maximum value
max_value, max_index = torch.max(c.view(-1), 0)
max_row = max_index // c.size(1)
max_col = max_index % c.size(1)

# Find the index of the minimum value
min_value, min_index = torch.min(c.view(-1), 0)
min_row = min_index // c.size(1)
min_col = min_index % c.size(1)

# Print the results
print("Index of maximum value:", (max_row.item(), max_col.item()))
print("Index of minimum value:", (min_row.item(), min_col.item()))

print(torch.cuda.is_available())
if torch.cuda.is_available():
   a = a.cuda()
   b = b.cuda()
print('a.device = ',a.device)
print('b.device = ',b.device)

Index of maximum value: (0, 2)
Index of minimum value: (1, 2)
True
a.device =  cuda:0
b.device =  cuda:0


In [11]:
#Q11
# Set the seed for reproducibility
torch.manual_seed(7)

# Create a random tensor with shape (1, 1, 1, 10)
tensor_with_singleton_dims = torch.randn(1, 1, 1, 10)

# Remove singleton dimensions to get a tensor of shape (10)
tensor_without_singleton_dims = tensor_with_singleton_dims.squeeze()

# Print the first tensor and its shape
print("Original tensor:")
print(tensor_with_singleton_dims)
print("Shape of original tensor:", tensor_with_singleton_dims.shape)

# Print the second tensor and its shape
print("\nTensor without singleton dimensions:")
print(tensor_without_singleton_dims)
print("Shape of tensor without singleton dimensions:", tensor_without_singleton_dims.shape)

print(torch.cuda.is_available())
if torch.cuda.is_available():
   a = a.cuda()
   b = b.cuda()
print('a.device = ',a.device)
print('b.device = ',b.device)

Original tensor:
tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,
            1.2324,  0.1382, -1.6822]]]])
Shape of original tensor: torch.Size([1, 1, 1, 10])

Tensor without singleton dimensions:
tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,  1.2324,
         0.1382, -1.6822])
Shape of tensor without singleton dimensions: torch.Size([10])
True
a.device =  cuda:0
b.device =  cuda:0
